name: flutter_other_plugin_example
description: Demonstrates how to use the flutter_other_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_other_plugin:
    path: ../


flutter:

  uses-material-design: true

  assets:
  - assets/msgSound.mp3

