name: flutter_other_plugin
description: This is a plugin for saving images and getting locations
version: 0.0.4
author: Will <willzh@live.cn>
homepage: https://github.com/20156284/flutter_other_plugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.willcheung.flutterotherplugin
    pluginClass: FlutterOtherPlugin
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"



